resources:
- https://github.com/matousjobanek/application-service/config/kcp?ref=241147d89d01bc8902751ac87d02e2928422e2b7

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: 67465f8dece31cde03e3c55d5adc35f21abf4de6

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
