---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-sre-admin
rules:
- apiGroups:
  - "toolchain.dev.openshift.com"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "groups"
  - "users"
  verbs:
  - "impersonate"
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "serviceaccounts/token"
  verbs:
  - "*"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "route.openshift.io"
  resources:
  - "routes"
  verbs:
  - "get"
  - "list"
  - "watch"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-sre-admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: MatousJobanek
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: alexeykazakov
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: xcoulon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sandbox-sre-admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: maintain-namespace
  namespace: toolchain-host-operator
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: MatousJobanek
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: alexeykazakov
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: xcoulon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
