kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: maintain-sandbox-sre
  namespace: sandbox-sre-host
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: MatousJobanek
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: alexeykazakov
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: xcoulon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
