apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: has
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cps-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: kcp
